### PR TITLE
Feature/add name field to transport

### PR DESCRIPTION
**Pull request by fredrikleknes**

### CODE REVIEW

**Review by petterwildhagen — COMMENTED** [review]
When I create a transport I cannot save it without specifying a cost time series. This works on substructure and topside

**Comment by ahmedoabdi** [comment]
The PR is missing the changes needed in the backend to allow sending empty/null profiles during create or update of Transport asset

**Review by petterwildhagen — APPROVED** [review]
Looks good!

**Review by ahmedoabdi — APPROVED** [review]
LGTM!

**Pull request merged**
